server:
  port: 8080
  servlet:
    context-path: /community

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    port: 465
    username: jhz222@qq.com
    password: ljnfzuwrqwwaidhd
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiahz.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# community
community:
  path:
    domain: http://localhost:8080
